/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * form.java
 *
 * Created on Dec 22, 2011, 7:37:38 PM
 */
package app.client.form;

import entity.mahasiswa;
import service.mahasiswaService;
import app.client.model.tabelmodelmahasiswa;
import java.rmi.RemoteException;
import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;



    /**
 *
 * @author paguman
 */
public class form extends javax.swing.JFrame {
    private tabelmodelmahasiswa tabelmodelmahasiswa = new tabelmodelmahasiswa();
    private mahasiswaService mahasiswaservice;
    
    
    /** Creates new form form
     * @param mahasiswaservice 
     */
    public form(mahasiswaService mahasiswaservice) {
        this.mahasiswaservice = mahasiswaservice;
        
        try {
            tabelmodelmahasiswa.setData(this.mahasiswaservice.getmahasiswa());

        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
        
        initComponents();         
                           
        TabelMahasiswa.setModel(tabelmodelmahasiswa);
                
          TabelMahasiswa.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
              
            public void valueChanged(ListSelectionEvent e) {
                int row =TabelMahasiswa.getSelectedRow();
                if (row != -1){
                    mahasiswa tblmahasiswa = tabelmodelmahasiswa.get(row);
                    textnama.setValue(tblmahasiswa.getNama());                   
                    textnim.setValue(tblmahasiswa.getNim());
                    textuts.setValue(tblmahasiswa.getUts());
                    textuas.setValue(tblmahasiswa.getUas());
                    texttugas.setValue(tblmahasiswa.getTugas());
                    if(tblmahasiswa.getJeniskelamin().equals("Pria"))
                        radiobuttonpria.setSelected(true);
                    else
                        radiobuttonwanita.setSelected(true);
                }
            }
        });        
        
    }
                      
    
/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textnama = new javax.swing.JFormattedTextField();
        radiobuttonpria = new javax.swing.JRadioButton();
        radiobuttonwanita = new javax.swing.JRadioButton();
        textnim = new javax.swing.JFormattedTextField();
        textuts = new javax.swing.JFormattedTextField();
        textuas = new javax.swing.JFormattedTextField();
        texttugas = new javax.swing.JFormattedTextField();
        buttonmasuk = new javax.swing.JButton();
        buttondelete = new javax.swing.JButton();
        buttonupdate = new javax.swing.JButton();
        buttonrefresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelMahasiswa = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Mahasiswa"));

        jLabel1.setText("Nama Mahasiswa");

        jLabel2.setText("Jenis Kelamin");

        jLabel3.setText("Nomor Induk Mahasiswa");

        jLabel4.setText("UTS");

        jLabel5.setText("UAS");

        jLabel6.setText("Tugas");

        buttonGroup1.add(radiobuttonpria);
        radiobuttonpria.setText("Pria");

        buttonGroup1.add(radiobuttonwanita);
        radiobuttonwanita.setText("Wanita");

        textnim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        textuts.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        textuas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        texttugas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(radiobuttonpria)
                        .addGap(18, 18, 18)
                        .addComponent(radiobuttonwanita))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textnama, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textnim, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textuts, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textuas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(texttugas, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(307, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(textnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radiobuttonpria)
                    .addComponent(radiobuttonwanita))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textnim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textuts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(texttugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        buttonmasuk.setText("Insert");
        buttonmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmasukActionPerformed(evt);
            }
        });

        buttondelete.setText("Delete");
        buttondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondeleteActionPerformed(evt);
            }
        });

        buttonupdate.setText("Update");
        buttonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonupdateActionPerformed(evt);
            }
        });

        buttonrefresh.setText("Refresh");
        buttonrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonrefreshActionPerformed(evt);
            }
        });

        TabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TabelMahasiswa);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 754, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(buttonmasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(buttondelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonmasuk)
                    .addComponent(buttondelete)
                    .addComponent(buttonupdate)
                    .addComponent(buttonrefresh))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void buttonmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmasukActionPerformed
        // TODO add your handling code here:
        try {       
            mahasiswa tblmahasiswa = new mahasiswa();
            tblmahasiswa.setNama(textnama.getText());
            if(radiobuttonpria.isSelected())
                tblmahasiswa.setJeniskelamin(radiobuttonpria.getText());
            else
                tblmahasiswa.setJeniskelamin(radiobuttonwanita.getText());
            tblmahasiswa.setNim(Integer.parseInt(textnim.getText()));
            tblmahasiswa.setUts(Integer.parseInt(textuts.getText()));
            tblmahasiswa.setUas(Integer.parseInt(textuas.getText()));
            tblmahasiswa.setTugas(Integer.parseInt(texttugas.getText()));
            float   avarage =   (float)(tblmahasiswa.getUts()+tblmahasiswa.getUas()+tblmahasiswa.getTugas())/3;
            tblmahasiswa.setAverage(avarage);
            mahasiswaservice.insertmahasiswa(tblmahasiswa);
            tabelmodelmahasiswa.insert(tblmahasiswa);
            

        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
}//GEN-LAST:event_buttonmasukActionPerformed

private void buttondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondeleteActionPerformed
        // TODO add your handling code here:
        try {            
            int row =TabelMahasiswa.getSelectedRow();

            if (row == -1){
                return;
            }
            Long id=tabelmodelmahasiswa.get(row).getId();
            mahasiswaservice.deletemahasiswa(id);
            tabelmodelmahasiswa.delete(row);           
            
        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
        
}//GEN-LAST:event_buttondeleteActionPerformed

private void buttonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonupdateActionPerformed
        // TODO add your handling code here:
        try {

            int row = TabelMahasiswa.getSelectedRow();                    
                    if (row == -1){
                        return;
                    }

            mahasiswa tblmahasiswa = tabelmodelmahasiswa.get(row);
            if(radiobuttonpria.isSelected())
                tblmahasiswa.setJeniskelamin(radiobuttonpria.getText());
            else
                tblmahasiswa.setJeniskelamin(radiobuttonwanita.getText());
            tblmahasiswa.setNama(textnama.getText());
            tblmahasiswa.setNim(Integer.parseInt(textnim.getText()));
            tblmahasiswa.setNim(Integer.parseInt(textnim.getText()));
            tblmahasiswa.setUts(Integer.parseInt(textuts.getText()));
            tblmahasiswa.setUas(Integer.parseInt(textuas.getText()));
            tblmahasiswa.setTugas(Integer.parseInt(texttugas.getText()));
            float   avarage =   (float)(tblmahasiswa.getUts()+tblmahasiswa.getUas()+tblmahasiswa.getTugas())/3;
            tblmahasiswa.setAverage(avarage);

            mahasiswaservice.updatemahasiswa(tblmahasiswa);
            tabelmodelmahasiswa.update(row, tblmahasiswa);
            
            List<mahasiswa> list = mahasiswaservice.getmahasiswa();
            tabelmodelmahasiswa.setData(list);

        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
}//GEN-LAST:event_buttonupdateActionPerformed

private void buttonrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonrefreshActionPerformed
        // TODO add your handling code here:
        try {
            List<mahasiswa> list = mahasiswaservice.getmahasiswa();
            tabelmodelmahasiswa.setData(list);            

        } catch (RemoteException exception) {
            exception.printStackTrace();
        }
}//GEN-LAST:event_buttonrefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelMahasiswa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buttondelete;
    private javax.swing.JButton buttonmasuk;
    private javax.swing.JButton buttonrefresh;
    private javax.swing.JButton buttonupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radiobuttonpria;
    private javax.swing.JRadioButton radiobuttonwanita;
    private javax.swing.JFormattedTextField textnama;
    private javax.swing.JFormattedTextField textnim;
    private javax.swing.JFormattedTextField texttugas;
    private javax.swing.JFormattedTextField textuas;
    private javax.swing.JFormattedTextField textuts;
    // End of variables declaration//GEN-END:variables

}